### ISSUE TITLE
OpenFaaS ASPNET Functions

### ISSUE THREAD

**Issue by goncalo-oliveira** [burtonr/OpenFaas.FunctionSDK#1]
Hi @burtonr,

May I suggest having a look at [OpenFaaS ASPNET Template](https://github.com/goncalo-oliveira/faas-aspnet-template)? It uses ASPNET 5 and provides a recognizable environment, including dependency injection, configuration, authorization. Contains C# and F# templates.

Cheers!

**Comment by burtonr** [comment]
This repo is over 2 years old. It was created while I was working on a version of the official OpenFaaS C# template while part of the Core team. This concept was not accepted, and therefor abandoned.

Thanks for letting me know this repo was still out there. I will archive it so this doesn't confuse anyone else.
